sudo: required
dist: trusty

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - latex-xcolor
      - pgf
      - lmodern

before_install:
  - openssl aes-256-cbc -K $encrypted_e1b54e14d2b1_key -iv $encrypted_e1b54e14d2b1_iv -in deploy_key.aes256.enc -out id_rsa -d
  - mv id_rsa ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa

script:
  - make
  - test -s main.pdf

after_success:
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis CI User"
  - mkdir -p /tmp/deploy
  - mv main.pdf /tmp/deploy/genomizer-manual.pdf
  - cd /tmp/deploy
  - git init
  - git add .
  - git commit -m "Deploy to GitHub ($(date))."
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && git push --force --quiet git@github.com:genomizer/genomizer-downloads.git master:documentation
