install:
  - git clone https://github.com/scottkosty/install-tl-ubuntu.git
  - sudo apt-get install -y libfile-fcntllock-perl gcc equivs libwww-perl fontconfig unzip
  - sudo install-tl-ubuntu/install-tl-ubuntu

script:
  - make
  - test -s main.pdf
