sudo: required
dist: trusty

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - latex-xcolor

script:
  - make
  - test -s main.pdf
