sudo: required
dist: trusty

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - latex-xcolor
      - pgf
      - lmodern

branches:
  except:
    - deploy

before_install:
  - openssl aes-256-cbc -K $encrypted_e1b54e14d2b1_key -iv $encrypted_e1b54e14d2b1_iv -in deploy/id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa

script:
  - make
  - test -s main.pdf

after_success:
  - mkdir deploy/out
  - mv main.pdf deploy/out/main.pdf
  - cd deploy/out
  - git init
  - git add .
  - git commit -m "Deploy to GitHub ($(date))."
  - ssh -T git@github.com
  - git push --force --quiet git@github.com:genomizer/genomizer-deployment-area.git master:documentation
